### ISSUE TITLE
Make dialyzer fails

### ISSUE THREAD

**Issue by madhavan020985** [lpgauth/kv#1]
I git cloned and ran, `make dialyzer`. It throws error as,

````
dialyzer: Unknown option: ebin/*.beam
make: *** [dialyzer] Error 1
````
i am seeing neither `ebin` folder nor there is `.beam files` inside this repository.
And the other make subcommands are also not working

**Comment by madhavan020985** [comment]
I ran `rebar compile`. It says, `Dependency not available` as,
````
kv$ rebar compile
==> kv (compile)
Dependency not available: lager-2.0.3 ({git,
                                        "https://github.com/basho/lager.git",
                                        {tag,"2.0.3"}})
Dependency not available: cowboy-1.0.3 ({git,
                                         "https://github.com/ninenines/cowboy.git",
                                         {tag,"1.0.3"}})
````

**Comment by madhavan020985** [comment]
I ran, `rebar get-deps`. It fails with the error, 
````
Cloning into 'parse_trans'...
ERROR: Dependency dir /home/sk/ws/kv/deps/parse_trans failed application validation with reason:
{version_mismatch,{"/home/sk/ws/kv/deps/parse_trans/src/parse_trans.app.src",
                   {expected,"2.9.2"},
                   {has,"2.9.1-2-ga06df66"}}}.
````.

**Comment by lpgauth** [comment]
Hi,
Yes, you need to build the app with make all first. As for the dependency issue that's weird.

Are you part fo the workshop? I've actually moved the code into separate repository. 

https://github.com/lpgauth/ms

**Comment by madhavan020985** [comment]
yes, i am very much in... i resolved it by changing the dependency version to wildcard character,
in deps/ms_base/rebar.config
````
{parse_trans, ".*",
        {git, "https://github.com/uwiger/parse_trans.git", {tag, "2.9.2"}}}
````

**Comment by lpgauth** [comment]
FYI, I just pushed the last changes to: https://github.com/lpgauth/ms
